[window]
opacity = 0.95
blur = true
option_as_alt = "Both"

[mouse]
hide_when_typing = false

[font]
normal = { family = "Cascadia Mono NF", style = "Regular" }
size = 11


[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\u001b\r" },
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
