[homelab_garage]
type = s3
provider = Other
env_auth = true
region = home
endpoint = https://storage.winetree94.com
acl = private
bucket_acl = private

[hetzner_fsn]
type = s3
provider = Other
env_auth = true
region = fsn1
endpoint = https://fsn1.your-objectstorage.com
acl = private
bucket_acl = private

[hetzner_hel]
type = s3
provider = Other
env_auth = true
region = hel1
endpoint = https://hel1.your-objectstorage.com
acl = private
bucket_acl = private
